final_project/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:medicine_id>', views.cart_add, name='cart_add'),
    path('remove/<int:medicine_id>', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('e_drugs.urls')),
]

final_project/cart/models.py
from django.db import models

# Create your models here.

final_project/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

final_project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from e_drugs.models import Medicine
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, medicine_id):
    cart = Cart(request)
    medicine = get_object_or_404(Medicine, id=medicine_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(medicine=medicine, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, medicine_id):
    cart = Cart(request)
    medicine = get_object_or_404(Medicine, id=medicine_id)
    cart.remove(medicine)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
    return render(request, 'detail.html', {'cart': cart})

final_project/cart/templates/detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% if cart %}
    <h1>Your shopping cart</h1>
    <table class="cart-table">
        <thead>
        <tr class="cart-style">
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
        {% with medicine=item.medicine %}
        <tr class="center">
            <td class="center">
                <img src="{% if med.image %}{{ med.image.url }}{% else %}{{ '../static/no-image.png' }}{% endif %}" width="100" height="100">
            </td>
            <td>
                <h3>{{ medicine.name }}</h3>
            </td>
            <td>
                <form style="margin-block-end: 0;" action="{% url 'cart:cart_add' medicine.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input class="btn btn-primary" type="submit" value="Update">
                    {% csrf_token %}
                </form>
            </td>
            <td>
                <form style="margin-block-end: 0;" action="{% url 'cart:cart_remove' medicine_id=medicine.id %}" method="post">
                    <input class="btn btn-danger" type="submit" value="Remove">
                    {% csrf_token %}
                </form>
            </td>
            <td>
                <p>${{ item.price }}</p>
            </td>
            <td>
                <p>${{ item.total_price }}</p>
            </td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="cart-style">
            <td>Total</td>
            <td colspan="4"></td>
            <td>${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
{% else %}
    <h1>Your shopping cart is empty.</h1>
{% endif %}


<p class="text-right">
    <a href="{% url 'medicines-all' %}" class="btn btn-info">Continue shopping</a>
    {% if cart %}
        {% if user.is_authenticated %}
            <a href="{% url 'order-create' %}" class="btn btn-info">Checkout</a>
        {% else %}
            <a href="{% url 'login' %}" class="btn btn-info">Login</a>
        {% endif %}
    {% endif %}
</p>
{% endblock %}